app:
  replicaCount: 2
  image:
    repository: tesseractdev12/swimlane-project
    tag: "v1.0.2"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3000
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

mongodb:
  replicaCount: 2
  image:
    repository: mongo
    tag: "6.0"
    pullPolicy: IfNotPresent
  persistence:
    size: 2Gi
  replSetName: rs0
  database: devops
  connectionString: ""
  # connectionString: "mongodb://swimlane-mongodb-0.swimlane-mongodb:27017,swimlane-mongodb-1.swimlane-mongodb:27017/devops?replicaSet=rs0"
  
ingress:
  enabled: true
  host: localhost
  tls:
    enabled: false

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpu:
    averageUtilization: 70

rbac:
  enabled: false
  # If true, a ServiceAccount, Role, and RoleBinding will be created for the app

networkPolicy:
  enabled: false
  # If true, NetworkPolicies will be applied:
  #  - Allow app pods to talk only to MongoDB
  #  - Allow ingress-nginx to reach app pods
