apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-mongodb-access
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: swimlane-mongodb
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: swimlane-app
      ports:
        - protocol: TCP
          port: 27017
  policyTypes:
    - Ingress
